/**:
  ros__parameters:
    # -- publishing period --
    curvature_interval_length_: 5.0
    prevent_zero_division_value: 0.001
    odom_interval_: 1
    acceptable_min_waypoint_distance: 2.0
    low_pass_filter_gain: 0.95
